### ISSUE TITLE
[Feature Request] Copy Folder Command

### ISSUE THREAD

**Issue by FelipeRearden** [kzhovn/copy-command-obsidian#1]
Hello @kzhovn !!!

Would be amazing to have the same function applied to folders! 
- Command Palette
- Context Menu

As mentioned here: https://discord.com/channels/686053708261228577/855181471643861002/890333429894381578

Thanks for reading and I wish you a great day!

**Comment by kzhovn** [comment]
Added in [0.2.0](https://github.com/kzhovn/copy-command-obsidian/releases/tag/0.2.0). Not available through the command palette or file dropdown menu, because it doesn't seem intuitive which folder would be copied, but in the file explorer menu.

**Comment by FelipeRearden** [comment]
Thanks for this feature!

> "Copy folder" command which copies the selected folder and all its contents.

I found something that I think I should share with you:

When the target folder is placed in the vault folder (root), the plugin creates a new folder but the content inside that folder in not copied (empty folder)

When the target folder is placed inside another folder (subfolder), the plugin works perfect (create a new folder + all its content)

Example:

- Not working when copying .../vault/folderA
- working when copying .../vault/folderA/folderA1

Obsidian 0.12.15 
Windows 10

**Comment by kzhovn** [comment]
Thanks for finding the bug! Should be fixed with [0.2.1](https://github.com/kzhovn/copy-command-obsidian/releases/tag/0.2.1), let me know if you have any other issues.

**Comment by FelipeRearden** [comment]
Hello @kzhovn!

100% perfect in version `0.2.1`.

Thank very much for this fix!
